config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  resources :users do
    member do
      get 'followings'
      get 'followers'
      get 'favorites'
    end
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  has_many :favorites
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  # 画像のアップローダー
  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase}
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
    has_secure_password
    
    validates :introduce, length: {maximum: 255}, allow_blank: true
    validates :homepage, allow_blank: true, format: /\A#{URI::regexp(%w(http https))}\z/, length: {maximum: 255}
    validates :location, allow_blank: true,  length: {maximum: 255}
    
    has_many :microposts
    
    has_many :following_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
    has_many :following_users, through: :following_relationships, source: :followed
    
    has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower
    

    
    #メソッドの追加
    #他のユーザーをフォローする
    def follow(other_user)
        following_relationships.find_or_create_by(followed_id: other_user.id)
    end
    
    #フォローしているユーザーのフォローを外す
    def unfollow(other_user)
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end
    
    #フォローしているかどうか
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    #自分とフォローしてるユーザのつぶやきを取得
    def feed_items
        Micropost.where(user_id: following_user_ids + [self.id])
    end
    
    
    
    has_many :favorites
    has_many :favorite_id, through: :favorites, source: :micropost
    
    # お気に入り登録
    def register_favorite(other_post)
        favorites.find_or_create_by(micropost_id: other_post.id)
    end
    
    # お気に入り解除
    def destroy_favorite(other_post)
        favorite = favorites.find_by(micropost_id: other_post.id)
        favorite.destroy if favorite
    end
    
    def favoriting?(other_post)
        favorite_id.include?(other_post)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  # ▼ログインしてなかったらログイン画面にリダイレクトさせる
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        @micropost = Micropost.find(params[:micropost_id])
        current_user.register_favorite(@micropost)
    end
    
    def destroy
        @micropost = Micropost.find_by(id: params[:micropost_id])
        current_user.destroy_favorite(@micropost)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = '投稿されました' 
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.include(:user).order(created_at: :desc)
     render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content, :image, :image_cache)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed_items.page(params[:page]).per(5).includes(:user).order(created_at: :desc)
    end
    @micropost = current_user.microposts.build if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login, only: [:edit, :update, :favorites]
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page]).per(5).order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "welcom to my app"
      redirect_to @user
    else
      render "new"
    end
  end
  
  
  def edit
    @user = User.find(params[:id])
    # ユーザーを比較するプライベートメソッドを作成し、befroe_actionでeditとupdateに適用させる。
    # @user = User.find(params[:id])
    # if current_user != @user
    # redirect_to root_url
    # end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: '会員情報を更新しました。'
    else
      render 'edit'
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.following_users
  end
  
  def followers
    @user = User.find(params[:id])
    @followings = @user.follower_users
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorite_id.page(params[:page]).per(5)
    # @microposts = @favorites.microposts.order(created_at: :desc)
  end
  
  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :location, :introduce, :homepage, :birthday)
  end
  
  def check_login
    @user = User.find(params[:id])
    if current_user != @user
    redirect_to root_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # current_userの返り値はuserモデルのインスタンス
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    # current_userに値が入っていればtrueを返す
    def logged_in?
       !!current_user
    end
    
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url ="https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/favorites/create.js.erb
$("#post-<%= @micropost.id %>").html("<%= escape_javascript(render('users/unfavorite')) %>");

app/views/favorites/destroy.js.erb
$("#post-<%= @micropost.id %>").html("<%= escape_javascript(render('users/favorite')) %>");

app/views/layouts/_aside.html.erb
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <ul class="other-links">
      <li>
        <%= link_to user_path(@user) do %>
        <span class="s-txt">ツイート</span>
        <span class="num"><%= @user.microposts.count %></span>
        <% end %>
      </li>
      <li>
        <%= link_to followings_user_path(@user) do %>
        <span class="s-txt">フォロー</span>
        <span class="num"><%= @user.following_users.count %></span>
        <% end %>
      </li>
      <li>
        <%= link_to followers_user_path(@user) do %>
        <span class="s-txt">フォロワー</span>
        <span class="num"><%= @user.follower_users.count %></span>
        <% end %>
      </li>
    </ul>
     <% if @user == current_user %>
     <div class="other-info">
       <ul class="other-info-lists">
         <% unless @user.birthday.blank? %>
         <li>
           <p class="info-ttl">誕生日</p>
           <p class="info-content"><%= @user.birthday.try(:strftime, "%Y年%m月%d日") %></p>
         </li>
         <% end %>
          <% unless @user.location.blank? %>
         <li>
           <p class="info-ttl">地域</p>
           <p class="info-content"><%= @user.location %></p>
         </li>
         <% end %>
         <% unless @user.homepage.blank? %>
         <li>
           <p class="info-ttl">ホームページ</p>
           <p class="info-content"><%= @user.homepage %></p>
         </li>
         <% end %>
       </ul>
     </div>
     <% end %>

app/views/layouts/_form.html.erb
      <div class="form-group">
      <%= f.label 'お名前' %>
      <%= f.text_field :name , class: 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label 'メールアドレス' %>
      <%= f.text_field :email , class: 'form-control'%>
      </div>
      <div class="form-group">
      <%= f.label 'パスワード' %>
      <%= f.password_field :password , class: 'form-control'%>
      </div>
      <div class="form-group">
      <%= f.label 'パスワード※確認用' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="form-inline">
      <div class="form-group">
      <%= f.label '誕生日' %>
      <%= f.date_select :birthday, {start_year: 1940, end_year: Time.now.year, use_month_numbers: true}, {class: "form-control"} %>
      </div>
      </div>
      <div class="form-group">
      <%= f.label '自己紹介' %>
      <%= f.text_area :introduce, class: 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label 'ホームページ' %>
      <%= f.text_field :homepage , class: 'form-control'%>
      </div>
      <div class="form-group">
      <%= f.label '地域' %>
      <%= f.text_field :location, class: 'form-control' %>
      </div>
      

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Microposts", "#", id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", "#" %></li>
              <% if logged_in? %>
                  <li><%= link_to "Users", "#" %></li>
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                         Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Plofile", user_path(current_user) %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <li><%= link_to "Favorites", favorites_user_path(current_user) %></li>
                             <li class="divider"></li>
                             <li><%= link_to "log out", logout_path, method:"delete" %></li>
                             <li><%= link_to "wantランキング", logout_path %></li>
                        </ul>
                </li>
              
              <% else %>
                  <li><%= link_to "Log in", login_path %></li>
              <% end %>
          </ul>
        </nav>
    </div>
    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microposts</title>
     <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" class="micropost-list">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
        Posted<%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user == micropost.user %>
            <%= link_to '削除' , micropost, method: :delete, data: {confirm: '本当に削除してもいいですか？' } %>        
        <% end %>
    </span>
    <% if micropost.image? %>
    <p>
        <%= image_tag micropost.image.thumb.url %>
       
    </p>
    <% end %>
    <% if logged_in? && current_user != micropost.user %>
    <div class="favorite_form" id="post-<%= micropost.id %>">
        <% if current_user.favoriting?(micropost) %>
            <%= form_for(current_user.favorites.find_by(micropost_id: micropost.id),
                html: { method: :delete},
                remote: true) do |f| %>
            <%= hidden_field_tag :micropost_id, micropost.id %>
            <%= f.submit '解除', class: "my-favorite unfavorite" %>
            <% end %>
                        
        <% else %>
        
            <%= form_for(current_user.favorites.build, remote: true) do |f| %>
            <%= hidden_field_tag :micropost_id, micropost.id %>
            <%= f.submit 'お気に入り', class: "my-favorite" %>
            <% end %>
            
        <% end %>

     </div>
    <% end %>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<%  end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
    <%= render @feed_items %>
</ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
    <%= f.text_area :content , placeholder: 'Compose new micropost...' %>
</div>
<div class="field post-image">
    <%= f.label '画像の添付' %>
    <!--<input type="file" class="filestyle" data-input="false">-->
    <%= f.file_field :image , class: 'filestyle', 'data-input'=> false %>
     <%= f.hidden_field :image_cache %>
</div>
    <%= f.submit '投稿する', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to 'プロフィールを見る', current_user %></span>
<span><%= pluralize(current_user.microposts.count, 'micropost') %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <section class="micropost_form">
            <%= render 'shared/micropost_form' %>
        </section>
    </aside>
    <div class="col-md-8">
      <h3>投稿フィード</h3>
      <%= render 'shared/feed' %>
      <%= paginate(@feed_items) %>
    </div>
</div>
<% else %>
<div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>
    <%= link_to 'ログインしてね！', signup_path, class: 'btn btn-lg btn-primary' %>
</div>
<% end %>

app/views/users/_favorite.html.erb
<%= form_for(current_user.favorites.build, remote: true) do |f| %>
<%= hidden_field_tag :micropost_id, @micropost.id %>
<%= f.submit 'お気に入り', class: "my-favorite" %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f|  %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_followlists.html.erb
<div class="person-block col-md-4">
  <%= link_to user_path(object), class: "person-link" do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <p><%= gravatar_for object %></p>
      <p class="name"><%= object.name %></p>
    </div>
  </div><!--/panel-->
  <% end %>
</div><!--/person-block-->

app/views/users/_unfavorite.html.erb
<%= form_for(current_user.favorites.find_by(micropost_id: @micropost.id),
    html: { method: :delete},
    remote: true) do |f| %>
    <%= hidden_field_tag :micropost_id, @micropost.id %>
<%= f.submit '解除', class: "my-favorite unfavorite" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "アンフォロー", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>編集画面</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f|  %>
     <%= render 'shared/error_messages', object: f.object %> 
     <%= render 'layouts/form', f: f %> 
      <%= f.submit '変更を保存' %>
    <% end  %>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render "layouts/aside" %>
  </aside>
  
  
  <div class="col-md-8">
   <h3>お気に入りリスト</h3>
   <% if @favorites.any? %>
     <ol class="microposts">
     <% @favorites.each do |favorite| %>
    <li id="micropost-<%= favorite.id %>" class="micropost-list">
    <%= link_to gravatar_for(favorite.user, size: 50), favorite.user %>
      <span class="user"><%= link_to favorite.user.name, favorite.user %></span>
      <span class="content"><%= favorite.content %></span>
      <span class="timestamp">
          Posted<%= time_ago_in_words(favorite.created_at) %> ago.
      </span>
    </li>
    <% end %>
    </ol>
    <%= paginate(@favorites) %>
    <% else %>
    <p class="bg-info no-microposts">お気に入りされた投稿はありません</p>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render "layouts/aside" %>
  </aside>
  <div class="col-md-8">
   <h2 class="text-left">フォロワ一覧</h2>
   <div class="wrp-block row">
     <% @followings.each do |following| %>
     
     <%= render "followlists", object: following %>
     <% end %>
   </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-md-4">
   <%= render "layouts/aside" %>
  </aside>
  <div class="col-md-8">
   <h2 class="text-left">フォローしてる人一覧</h2>
   <div class="wrp-block row">
     <% @followings.each do |following| %>
     <%= render "followlists", object: following %>
     <% end %>
   </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
   <%= render 'shared/error_messages', object: f.object %> 
      <%= render 'layouts/form', f: f %> 
      
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render "layouts/aside" %>
    
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>投稿 (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
    <%= paginate(@microposts) %>
  </div>
</div>